//! Autogenerated weights for `pallet_supply_chain_tracking`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2024-01-01, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `benchmark-host`, CPU: `Intel Core`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// target/release/parachain-node
// benchmark
// pallet
// --chain=dev
// --pallet=pallet_supply_chain_tracking
// --extrinsic=*
// --steps=50
// --repeat=20
// --output=pallets/supply-chain-tracking/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(clippy::unnecessary_cast)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_supply_chain_tracking`.
pub trait WeightInfo {
	fn create_tracking() -> Weight;
	fn add_event() -> Weight;
	fn update_status() -> Weight;
	fn update_location() -> Weight;
}

/// Weights for `pallet_supply_chain_tracking` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: TrackingRecords (r:1 w:1)
	/// Proof: TrackingRecords (max_values: None, max_size: Some(10000), added: 12475, mode: MaxEncodedLen)
	/// Storage: ProductTracking (r:0 w:1)
	/// Proof: ProductTracking (max_values: None, max_size: Some(64), added: 2539, mode: MaxEncodedLen)
	/// Storage: LocationProducts (r:0 w:1)
	/// Proof: LocationProducts (max_values: None, max_size: Some(64), added: 2539, mode: MaxEncodedLen)
	fn create_tracking() -> Weight {
		Weight::from_parts(55_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(3))
	}

	/// Storage: TrackingRecords (r:1 w:1)
	/// Proof: TrackingRecords (max_values: None, max_size: Some(10000), added: 12475, mode: MaxEncodedLen)
	/// Storage: LocationProducts (r:0 w:2)
	/// Proof: LocationProducts (max_values: None, max_size: Some(64), added: 2539, mode: MaxEncodedLen)
	fn add_event() -> Weight {
		Weight::from_parts(65_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(3))
	}

	/// Storage: TrackingRecords (r:1 w:1)
	/// Proof: TrackingRecords (max_values: None, max_size: Some(10000), added: 12475, mode: MaxEncodedLen)
	fn update_status() -> Weight {
		Weight::from_parts(35_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}

	/// Storage: TrackingRecords (r:1 w:1)
	/// Proof: TrackingRecords (max_values: None, max_size: Some(10000), added: 12475, mode: MaxEncodedLen)
	/// Storage: LocationProducts (r:0 w:2)
	/// Proof: LocationProducts (max_values: None, max_size: Some(64), added: 2539, mode: MaxEncodedLen)
	fn update_location() -> Weight {
		Weight::from_parts(45_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(3))
	}
}

// For tests and when no real weights are available
impl WeightInfo for () {
	fn create_tracking() -> Weight {
		Weight::from_parts(55_000_000, 0)
	}
	fn add_event() -> Weight {
		Weight::from_parts(65_000_000, 0)
	}
	fn update_status() -> Weight {
		Weight::from_parts(35_000_000, 0)
	}
	fn update_location() -> Weight {
		Weight::from_parts(45_000_000, 0)
	}
}
