//! Autogenerated weights for `pallet_security`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2024-10-19

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame::deps::frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_security`.
pub trait WeightInfo {
	fn create_encryption_key() -> Weight;
	fn rotate_encryption_key() -> Weight;
	fn encrypt_data() -> Weight;
	fn create_audit_log() -> Weight;
	fn export_audit_logs() -> Weight;
	fn create_backup() -> Weight;
	fn configure_backup_schedule() -> Weight;
	fn create_recovery_point() -> Weight;
	fn enable_mfa() -> Weight;
	fn register_mfa_device() -> Weight;
	fn verify_mfa() -> Weight;
	fn register_oauth_provider() -> Weight;
	fn connect_oauth() -> Weight;
	fn create_session() -> Weight;
	fn revoke_session() -> Weight;
	fn whitelist_ip() -> Weight;
	fn blacklist_ip() -> Weight;
	fn record_failed_login() -> Weight;
	fn update_security_policy() -> Weight;
}

/// Weights for `pallet_security` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame::deps::frame_system::Config> WeightInfo for SubstrateWeight<T> {
	fn create_encryption_key() -> Weight {
		Weight::from_parts(60_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(2))
	}

	fn rotate_encryption_key() -> Weight {
		Weight::from_parts(55_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(2))
	}

	fn encrypt_data() -> Weight {
		Weight::from_parts(40_000_000, 0)
			.saturating_add(T::DbWeight::get().writes(2))
	}

	fn create_audit_log() -> Weight {
		Weight::from_parts(45_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(3))
	}

	fn export_audit_logs() -> Weight {
		Weight::from_parts(100_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}

	fn create_backup() -> Weight {
		Weight::from_parts(80_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(3))
	}

	fn configure_backup_schedule() -> Weight {
		Weight::from_parts(35_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}

	fn create_recovery_point() -> Weight {
		Weight::from_parts(50_000_000, 0)
			.saturating_add(T::DbWeight::get().writes(2))
	}

	fn enable_mfa() -> Weight {
		Weight::from_parts(55_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(2))
	}

	fn register_mfa_device() -> Weight {
		Weight::from_parts(45_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(2))
	}

	fn verify_mfa() -> Weight {
		Weight::from_parts(40_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(2))
	}

	fn register_oauth_provider() -> Weight {
		Weight::from_parts(40_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}

	fn connect_oauth() -> Weight {
		Weight::from_parts(50_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}

	fn create_session() -> Weight {
		Weight::from_parts(55_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}

	fn revoke_session() -> Weight {
		Weight::from_parts(45_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(3))
	}

	fn whitelist_ip() -> Weight {
		Weight::from_parts(40_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(2))
	}

	fn blacklist_ip() -> Weight {
		Weight::from_parts(40_000_000, 0)
			.saturating_add(T::DbWeight::get().writes(1))
	}

	fn record_failed_login() -> Weight {
		Weight::from_parts(45_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}

	fn update_security_policy() -> Weight {
		Weight::from_parts(30_000_000, 0)
			.saturating_add(T::DbWeight::get().writes(1))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	fn create_encryption_key() -> Weight {
		Weight::from_parts(60_000_000, 0)
	}
	fn rotate_encryption_key() -> Weight {
		Weight::from_parts(55_000_000, 0)
	}
	fn encrypt_data() -> Weight {
		Weight::from_parts(40_000_000, 0)
	}
	fn create_audit_log() -> Weight {
		Weight::from_parts(45_000_000, 0)
	}
	fn export_audit_logs() -> Weight {
		Weight::from_parts(100_000_000, 0)
	}
	fn create_backup() -> Weight {
		Weight::from_parts(80_000_000, 0)
	}
	fn configure_backup_schedule() -> Weight {
		Weight::from_parts(35_000_000, 0)
	}
	fn create_recovery_point() -> Weight {
		Weight::from_parts(50_000_000, 0)
	}
	fn enable_mfa() -> Weight {
		Weight::from_parts(55_000_000, 0)
	}
	fn register_mfa_device() -> Weight {
		Weight::from_parts(45_000_000, 0)
	}
	fn verify_mfa() -> Weight {
		Weight::from_parts(40_000_000, 0)
	}
	fn register_oauth_provider() -> Weight {
		Weight::from_parts(40_000_000, 0)
	}
	fn connect_oauth() -> Weight {
		Weight::from_parts(50_000_000, 0)
	}
	fn create_session() -> Weight {
		Weight::from_parts(55_000_000, 0)
	}
	fn revoke_session() -> Weight {
		Weight::from_parts(45_000_000, 0)
	}
	fn whitelist_ip() -> Weight {
		Weight::from_parts(40_000_000, 0)
	}
	fn blacklist_ip() -> Weight {
		Weight::from_parts(40_000_000, 0)
	}
	fn record_failed_login() -> Weight {
		Weight::from_parts(45_000_000, 0)
	}
	fn update_security_policy() -> Weight {
		Weight::from_parts(30_000_000, 0)
	}
}
