//! Autogenerated weights for `pallet_product_management`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2024-01-01, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `benchmark-host`, CPU: `Intel Core`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// target/release/parachain-node
// benchmark
// pallet
// --chain=dev
// --pallet=pallet_product_management
// --extrinsic=*
// --steps=50
// --repeat=20
// --output=pallets/product-management/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(clippy::unnecessary_cast)]

use frame::deps::frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_product_management`.
pub trait WeightInfo {
	fn create_product() -> Weight;
	fn update_product_status() -> Weight;
	fn add_attribute() -> Weight;
	fn update_attribute() -> Weight;
}

/// Weights for `pallet_product_management` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame::deps::frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: Products (r:0 w:1)
	/// Proof: Products (max_values: None, max_size: Some(500), added: 2975, mode: MaxEncodedLen)
	/// Storage: CompanyProducts (r:0 w:1)
	/// Proof: CompanyProducts (max_values: None, max_size: Some(64), added: 2539, mode: MaxEncodedLen)
	/// Storage: NextProductId (r:1 w:1)
	/// Proof: NextProductId (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
	/// Storage: Categories (r:1 w:1)
	/// Proof: Categories (max_values: None, max_size: Some(132), added: 2607, mode: MaxEncodedLen)
	fn create_product() -> Weight {
		Weight::from_parts(60_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(4))
	}

	/// Storage: Products (r:1 w:1)
	/// Proof: Products (max_values: None, max_size: Some(500), added: 2975, mode: MaxEncodedLen)
	fn update_product_status() -> Weight {
		Weight::from_parts(35_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}

	/// Storage: Products (r:1 w:1)
	/// Proof: Products (max_values: None, max_size: Some(500), added: 2975, mode: MaxEncodedLen)
	fn add_attribute() -> Weight {
		Weight::from_parts(45_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}

	/// Storage: Products (r:1 w:1)
	/// Proof: Products (max_values: None, max_size: Some(500), added: 2975, mode: MaxEncodedLen)
	fn update_attribute() -> Weight {
		Weight::from_parts(40_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}

// For tests and when no real weights are available
impl WeightInfo for () {
	fn create_product() -> Weight {
		Weight::from_parts(60_000_000, 0)
	}
	fn update_product_status() -> Weight {
		Weight::from_parts(35_000_000, 0)
	}
	fn add_attribute() -> Weight {
		Weight::from_parts(45_000_000, 0)
	}
	fn update_attribute() -> Weight {
		Weight::from_parts(40_000_000, 0)
	}
}
