//! Autogenerated weights for `pallet_company_management`

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(clippy::unnecessary_cast)]

use frame::deps::frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

pub trait WeightInfo {
	fn create_company() -> Weight;
	fn invite_member() -> Weight;
	fn accept_invitation() -> Weight;
	fn reject_invitation() -> Weight;
	fn remove_member() -> Weight;
	fn transfer_ownership() -> Weight;
	fn verify_company() -> Weight;
}

pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame::deps::frame_system::Config> WeightInfo for SubstrateWeight<T> {
	fn create_company() -> Weight {
		Weight::from_parts(60_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	fn invite_member() -> Weight {
		Weight::from_parts(40_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	fn accept_invitation() -> Weight {
		Weight::from_parts(50_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(4))
	}
	fn reject_invitation() -> Weight {
		Weight::from_parts(30_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
	fn remove_member() -> Weight {
		Weight::from_parts(45_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	fn transfer_ownership() -> Weight {
		Weight::from_parts(40_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(3))
	}
	fn verify_company() -> Weight {
		Weight::from_parts(35_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}

impl WeightInfo for () {
	fn create_company() -> Weight { Weight::from_parts(60_000_000, 0) }
	fn invite_member() -> Weight { Weight::from_parts(40_000_000, 0) }
	fn accept_invitation() -> Weight { Weight::from_parts(50_000_000, 0) }
	fn reject_invitation() -> Weight { Weight::from_parts(30_000_000, 0) }
	fn remove_member() -> Weight { Weight::from_parts(45_000_000, 0) }
	fn transfer_ownership() -> Weight { Weight::from_parts(40_000_000, 0) }
	fn verify_company() -> Weight { Weight::from_parts(35_000_000, 0) }
}
