//! Autogenerated weights for `pallet_external_integrations`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2024-10-19

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_external_integrations`.
pub trait WeightInfo {
	fn create_api_key() -> Weight;
	fn revoke_api_key() -> Weight;
	fn create_import_job() -> Weight;
	fn create_export_job() -> Weight;
	fn queue_email() -> Weight;
	fn update_email_template() -> Weight;
	fn register_barcode() -> Weight;
	fn scan_barcode() -> Weight;
	fn register_webhook() -> Weight;
}

/// Weights for `pallet_external_integrations` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `ExternalIntegrations::ApiKeys` (r:1 w:1)
	/// Proof: `ExternalIntegrations::ApiKeys` (`max_values`: None, `max_size`: Some(1024), added: 3499, mode: `MaxEncodedLen`)
	/// Storage: `ExternalIntegrations::UserApiKeys` (r:1 w:1)
	/// Proof: `ExternalIntegrations::UserApiKeys` (`max_values`: None, `max_size`: Some(2048), added: 4523, mode: `MaxEncodedLen`)
	fn create_api_key() -> Weight {
		Weight::from_parts(50_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}

	/// Storage: `ExternalIntegrations::ApiKeys` (r:1 w:1)
	/// Proof: `ExternalIntegrations::ApiKeys` (`max_values`: None, `max_size`: Some(1024), added: 3499, mode: `MaxEncodedLen`)
	/// Storage: `ExternalIntegrations::UserApiKeys` (r:1 w:1)
	/// Proof: `ExternalIntegrations::UserApiKeys` (`max_values`: None, `max_size`: Some(2048), added: 4523, mode: `MaxEncodedLen`)
	fn revoke_api_key() -> Weight {
		Weight::from_parts(40_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}

	/// Storage: `ExternalIntegrations::ImportJobs` (r:0 w:1)
	/// Proof: `ExternalIntegrations::ImportJobs` (`max_values`: None, `max_size`: Some(2048), added: 4523, mode: `MaxEncodedLen`)
	fn create_import_job() -> Weight {
		Weight::from_parts(30_000_000, 0)
			.saturating_add(T::DbWeight::get().writes(1))
	}

	/// Storage: `ExternalIntegrations::ExportJobs` (r:0 w:1)
	/// Proof: `ExternalIntegrations::ExportJobs` (`max_values`: None, `max_size`: Some(2048), added: 4523, mode: `MaxEncodedLen`)
	fn create_export_job() -> Weight {
		Weight::from_parts(30_000_000, 0)
			.saturating_add(T::DbWeight::get().writes(1))
	}

	/// Storage: `ExternalIntegrations::EmailTemplates` (r:1 w:0)
	/// Proof: `ExternalIntegrations::EmailTemplates` (`max_values`: None, `max_size`: Some(1024), added: 3499, mode: `MaxEncodedLen`)
	/// Storage: `ExternalIntegrations::EmailQueue` (r:0 w:1)
	/// Proof: `ExternalIntegrations::EmailQueue` (`max_values`: None, `max_size`: Some(4096), added: 6571, mode: `MaxEncodedLen`)
	/// Storage: `ExternalIntegrations::EmailDeliveryStatus` (r:0 w:1)
	/// Proof: `ExternalIntegrations::EmailDeliveryStatus` (`max_values`: None, `max_size`: Some(512), added: 2987, mode: `MaxEncodedLen`)
	fn queue_email() -> Weight {
		Weight::from_parts(45_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(2))
	}

	/// Storage: `ExternalIntegrations::EmailTemplates` (r:0 w:1)
	/// Proof: `ExternalIntegrations::EmailTemplates` (`max_values`: None, `max_size`: Some(1024), added: 3499, mode: `MaxEncodedLen`)
	fn update_email_template() -> Weight {
		Weight::from_parts(25_000_000, 0)
			.saturating_add(T::DbWeight::get().writes(1))
	}

	/// Storage: `ExternalIntegrations::BarcodeRegistry` (r:1 w:1)
	/// Proof: `ExternalIntegrations::BarcodeRegistry` (`max_values`: None, `max_size`: Some(512), added: 2987, mode: `MaxEncodedLen`)
	fn register_barcode() -> Weight {
		Weight::from_parts(35_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}

	/// Storage: `ExternalIntegrations::BarcodeRegistry` (r:1 w:1)
	/// Proof: `ExternalIntegrations::BarcodeRegistry` (`max_values`: None, `max_size`: Some(512), added: 2987, mode: `MaxEncodedLen`)
	fn scan_barcode() -> Weight {
		Weight::from_parts(30_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}

	/// Storage: `ExternalIntegrations::Webhooks` (r:1 w:1)
	/// Proof: `ExternalIntegrations::Webhooks` (`max_values`: None, `max_size`: Some(2048), added: 4523, mode: `MaxEncodedLen`)
	fn register_webhook() -> Weight {
		Weight::from_parts(35_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}

// For backwards compatibility and tests.
impl WeightInfo for () {
	fn create_api_key() -> Weight {
		Weight::from_parts(50_000_000, 0)
	}
	fn revoke_api_key() -> Weight {
		Weight::from_parts(40_000_000, 0)
	}
	fn create_import_job() -> Weight {
		Weight::from_parts(30_000_000, 0)
	}
	fn create_export_job() -> Weight {
		Weight::from_parts(30_000_000, 0)
	}
	fn queue_email() -> Weight {
		Weight::from_parts(45_000_000, 0)
	}
	fn update_email_template() -> Weight {
		Weight::from_parts(25_000_000, 0)
	}
	fn register_barcode() -> Weight {
		Weight::from_parts(35_000_000, 0)
	}
	fn scan_barcode() -> Weight {
		Weight::from_parts(30_000_000, 0)
	}
	fn register_webhook() -> Weight {
		Weight::from_parts(35_000_000, 0)
	}
}
