//! Autogenerated weights for `pallet_role_permissions`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2024-01-01, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `benchmark-host`, CPU: `Intel Core`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// target/release/parachain-node
// benchmark
// pallet
// --chain=dev
// --pallet=pallet_role_permissions
// --extrinsic=*
// --steps=50
// --repeat=20
// --output=pallets/role-permissions/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(clippy::unnecessary_cast)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_role_permissions`.
pub trait WeightInfo {
	fn create_role() -> Weight;
	fn assign_role() -> Weight;
	fn revoke_role() -> Weight;
	fn update_role_permissions() -> Weight;
}

/// Weights for `pallet_role_permissions` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: UserRoles (r:1 w:0)
	/// Proof: UserRoles (max_values: None, max_size: Some(100), added: 2575, mode: MaxEncodedLen)
	/// Storage: Roles (r:0 w:1)
	/// Proof: Roles (max_values: None, max_size: Some(500), added: 2975, mode: MaxEncodedLen)
	/// Storage: CompanyRoles (r:0 w:1)
	/// Proof: CompanyRoles (max_values: None, max_size: Some(16), added: 2491, mode: MaxEncodedLen)
	/// Storage: NextRoleId (r:1 w:1)
	/// Proof: NextRoleId (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
	fn create_role() -> Weight {
		Weight::from_parts(50_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(3))
	}

	/// Storage: UserRoles (r:2 w:1)
	/// Proof: UserRoles (max_values: None, max_size: Some(100), added: 2575, mode: MaxEncodedLen)
	/// Storage: Roles (r:1 w:0)
	/// Proof: Roles (max_values: None, max_size: Some(500), added: 2975, mode: MaxEncodedLen)
	fn assign_role() -> Weight {
		Weight::from_parts(40_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(1))
	}

	/// Storage: UserRoles (r:2 w:1)
	/// Proof: UserRoles (max_values: None, max_size: Some(100), added: 2575, mode: MaxEncodedLen)
	fn revoke_role() -> Weight {
		Weight::from_parts(30_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}

	/// Storage: UserRoles (r:1 w:0)
	/// Proof: UserRoles (max_values: None, max_size: Some(100), added: 2575, mode: MaxEncodedLen)
	/// Storage: Roles (r:1 w:1)
	/// Proof: Roles (max_values: None, max_size: Some(500), added: 2975, mode: MaxEncodedLen)
	fn update_role_permissions() -> Weight {
		Weight::from_parts(35_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}

// For tests and when no real weights are available
impl WeightInfo for () {
	fn create_role() -> Weight {
		Weight::from_parts(50_000_000, 0)
	}
	fn assign_role() -> Weight {
		Weight::from_parts(40_000_000, 0)
	}
	fn revoke_role() -> Weight {
		Weight::from_parts(30_000_000, 0)
	}
	fn update_role_permissions() -> Weight {
		Weight::from_parts(35_000_000, 0)
	}
}
