//! Autogenerated weights for `pallet_user_management`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2024-01-01, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `benchmark-host`, CPU: `Intel Core`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// target/release/parachain-node
// benchmark
// pallet
// --chain=dev
// --pallet=pallet_user_management
// --extrinsic=*
// --steps=50
// --repeat=20
// --output=pallets/user-management/src/weights.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(clippy::unnecessary_cast)]

use frame::deps::frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use core::marker::PhantomData;

/// Weight functions needed for `pallet_user_management`.
pub trait WeightInfo {
	fn register_user() -> Weight;
	fn update_profile() -> Weight;
	fn submit_verification() -> Weight;
	fn approve_verification() -> Weight;
	fn reject_verification() -> Weight;
}

/// Weights for `pallet_user_management` using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame::deps::frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: Users (r:1 w:1)
	/// Proof: Users (max_values: None, max_size: Some(200), added: 2675, mode: MaxEncodedLen)
	/// Storage: EmailToAccount (r:1 w:1)
	/// Proof: EmailToAccount (max_values: None, max_size: Some(64), added: 2539, mode: MaxEncodedLen)
	/// Storage: UserCount (r:1 w:1)
	/// Proof: UserCount (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
	fn register_user() -> Weight {
		Weight::from_parts(50_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(3))
			.saturating_add(T::DbWeight::get().writes(3))
	}

	/// Storage: Users (r:1 w:1)
	/// Proof: Users (max_values: None, max_size: Some(200), added: 2675, mode: MaxEncodedLen)
	fn update_profile() -> Weight {
		Weight::from_parts(30_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}

	/// Storage: Users (r:1 w:0)
	/// Proof: Users (max_values: None, max_size: Some(200), added: 2675, mode: MaxEncodedLen)
	/// Storage: VerificationRequests (r:0 w:1)
	/// Proof: VerificationRequests (max_values: None, max_size: Some(300), added: 2775, mode: MaxEncodedLen)
	fn submit_verification() -> Weight {
		Weight::from_parts(40_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}

	/// Storage: VerificationRequests (r:1 w:1)
	/// Proof: VerificationRequests (max_values: None, max_size: Some(300), added: 2775, mode: MaxEncodedLen)
	/// Storage: Users (r:1 w:1)
	/// Proof: Users (max_values: None, max_size: Some(200), added: 2675, mode: MaxEncodedLen)
	fn approve_verification() -> Weight {
		Weight::from_parts(40_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(2))
			.saturating_add(T::DbWeight::get().writes(2))
	}

	/// Storage: VerificationRequests (r:1 w:1)
	/// Proof: VerificationRequests (max_values: None, max_size: Some(300), added: 2775, mode: MaxEncodedLen)
	fn reject_verification() -> Weight {
		Weight::from_parts(30_000_000, 0)
			.saturating_add(T::DbWeight::get().reads(1))
			.saturating_add(T::DbWeight::get().writes(1))
	}
}

// For tests and when no real weights are available
impl WeightInfo for () {
	fn register_user() -> Weight {
		Weight::from_parts(50_000_000, 0)
	}
	fn update_profile() -> Weight {
		Weight::from_parts(30_000_000, 0)
	}
	fn submit_verification() -> Weight {
		Weight::from_parts(40_000_000, 0)
	}
	fn approve_verification() -> Weight {
		Weight::from_parts(40_000_000, 0)
	}
	fn reject_verification() -> Weight {
		Weight::from_parts(30_000_000, 0)
	}
}
